# Note that all these variables can be accesses by liquid with {{site.my.name}}
# since this file is under global key (site).

timezone: Europe/Istanbul
markdown: kramdown
safe: true # Plugins are not allowed, since can not be used with github.io anyway
lsi: false # Disabled by github.io
relative-permalinks: false
permalink: /:categories/:title.html
highlighter: pygments
# Jekyll specific to _config.yml ( release/stable site)
destination: ./_site
exclude: [node_modules, bower_modules, scripts, styles, tmp]
show_drafts: nil
port: 4000
url: http://localhost:4000

# Non-jekyll project specific to _config_devel.yml ( devel site)
isDevelopmentBuild: false

# Localization
locale:
  tr:
    months:
      '01' : 'Ocak'
      '02' : 'Şubat'
      '03' : 'Mart'
      '04' : 'Nisan'
      '05' : 'Mayis'
      '06' : 'Haziran'
      '07' : 'Temmuz'
      '08' : 'Ağustos'
      '09' : 'Eylül'
      '10' : 'Ekim'
      '11' : 'Kasım'
      '12' : 'Aralık'

# User specific configuration
my:
  website: 'http://ahmetyeshil.com/'
  name: 'Ahmet Yeşil'
  email: 'ayesil#freeconsole.org'
  disqus_shortname: 'narzac'
  google_analytics:
    property_id: 'UA-42936972-1'
    site_name: 'ahmetyeshil.com'
  twitter:
    nick: 'narzac'
  github:
    nick: 'narzac'
    repo: 'narzac.github.io'
